public class Driver {
    public static void main(String[] args) {

        System.out.println("This output was Generated by Munira Tabassum");
        System.out.println("Exercise 1");
        System.out.println(" ");

        Card card1 = Card.randomCard();
        Card card2 = Card.randomCard();

        String result;
        if(card1.compareTo(card2) > 0) result = "bigger than ";
        else if(card1.compareTo(card2) == 0) result = "Equal to ";
        else result = "smaller than ";

        System.out.println(card1.toString() + " is " + result + card2.toString());
    }
}
